export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const CLEAR_REMINDERS = 'CLEAR_REMINDERS';
export const UNDO_REMINDERS = 'UNDO_REMINDERS';
export const REDO_REMINDERS = 'REDO_REMINDERS';
